<a href="https://colab.research.google.com/github/boseull/pytorch/blob/main/pytorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor : 배열과 행렬과 유사. Numpy ndarray와 유사. 자동 미분에 최적화.

In [14]:
import torch
import numpy as np

##텐서 초기화

In [15]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)  #데이터로부터 텐서 생성

In [16]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)  #numpy 배열로부터 텐서 생성

In [17]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2250, 0.8151],
        [0.6490, 0.3906]]) 



In [18]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7504, 0.5393, 0.2158],
        [0.6512, 0.0565, 0.6823]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



##텐서의 속성

In [19]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


##텐서 연산

In [20]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda') #GPU로 텐서를 이동

In [21]:
tensor.device

device(type='cuda', index=0)

In [22]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) #torch.cat 텐서 연결
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


##산술 연산

In [24]:
y1 = tensor @ tensor.T #'@' 행렬곱
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3) #값을 Y3에 저장
print(y1)
print(y2)
print(y3)

tensor([[0.6748, 0.0461, 0.4832, 0.4367],
        [0.4725, 0.9318, 0.2368, 0.5007],
        [0.4706, 0.7827, 0.0139, 0.0572],
        [0.2534, 0.7825, 0.6259, 0.8486]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [25]:
z1 = tensor * tensor #'*' 요소 곱
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)
print(z2)
print(z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
agg = tensor.sum()
print(agg)
#agg = agg + torch.tensor([1, 2])
#print(agg)
agg_item = agg.item() #item : 행렬의 요소가 1일 때, 행렬을 숫자값으로
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [27]:
print(tensor, "\n")
print(tensor.add_(5)) #바꿔치기 : 결과를 피연산자에 저장, '_'를 가짐
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


##Numpy 변환

In [28]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [29]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}") #자동으로 변경사항이 저장됨

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


##Numpy를 텐서로 변환

In [30]:
n = np.ones(5)
print(n)
t = torch.from_numpy(n)


[1. 1. 1. 1. 1.]


In [31]:
np.add(n, 1, out=n)
print(f"t : {t}") #변경 사항 자동 저장
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
